summary(indigenousearthquakedata)
rm(TOWN)
indigenousearthquakedata <- subset(indigenousearthquakedata, select = -TOWN)
indigenousearthquakedata <- subset(indigenousearthquakedata, select = -c(COUNTY, avg))
library(dplyr)
rename(indigenousearthquakedata, sum_of_earthquakes = Column2)
indigenousearthquakedata <-rename(indigenousearthquakedata, sum_of_earthquakes = Column2)
ls(indigenousearthquakedata)
indigenousearthquakedata <- mutate(indigenousearthquakedata, avgalter = sum_of_earthquakes/5)
ls(indigenousearthquakedata)
library(psych)
describe(indigenousearthquakedata)
table(indigenousearthquakedata$indigenous_township)
table(indigenousearthquakedata$avg_1)
grouping <- summarise(group_by(indigenousearthquakedata,indigenous_township), m = mean(avg_1), med = median(avg_1), min = min(avg_1), max = max(avg_1))
library(ggplot2)
print (grouping)
boxplot(indigenousearthquakedata$avg_1, main = "average number of earthquakes per townships", ylab = "5 years average", col = "blue")
boxplot(indigenousearthquakedata$avg_1, main = "average number of earthquakes per townshis", ylab = "5 years average", col = "blue")
boxplot(indigenousearthquakedata$spaci_2018, indigenousearthquakedata$Spaci_2019, indigenousearthquakedata$`SC-2020`,indigenousearthquakedata$SC, indigenousearthquakedata$SC_2022,  main = "earthquakes by township", names = c("2018", "2019", "2020", "2021", "2022"), ylab = "count", col = "blue")
barplot(grouping$m, main = "average number of earthquakes per 5 year", names = c("Non-indigenous townships", "Indigenous townships"))
        percentagearthquake <-lm(O_PER_num~avg_1, data = indigenousearthquakedata)
hist(indigenousearthquakedata$avg_1)
summary(percentagearthquake)
percentagearthquakerobust <- lmrob(O_PER_num ~ avg_1, data = indigenousearthquakedata)
library(robustbase)
summary(percentagearthquakerobust)
logit <- glm(indigenous_township ~ avg_1, data = indigenousearthquakedata)
logit
summary(logit)
plot(indigenousearthquakedata$O_PER_num, indigenousearthquakedata$avg_1, ylab= "Average number of earthquakes in last 5 years", xlab = "Percentage of indigenous people")
     abline (lm(indigenousearthquakedata$O_PER_num~indigenousearthquakedata$avg_1))
     
plot(indigenousearthquakedata$indigenous_township, indigenousearthquakedata$avg_1)
     abline (glm(indigenousearthquakedata$avg_1~indigenousearthquakedata$avg_1)).last.value
     
     cor.test(indigenousearthquakedata$avg_1, indigenousearthquakedata$indigenous_township, method = "pearson" )
     boxplot(indigenousearthquakedata$O_PER_num, ylab = "%",  xlab="Percentage of indigenous peoples per township")
     barplot(indigenousearthquakedata$indigenous_township
     ggplot(indigenousearthquakedata, aes(x=indigenous_township, fill = indigenous_township)) +
       geom_bar()
     barplot(prop.table(table(indigenousearthquakedata$indigenous_township)), xlab = "1 indigenous 0 non-indigenous", main = "Township categories")
     cor.test(indigenousearthquakedata$O_PER_num, indigenousearthquakedata$avg_1, method = "pearson" )
     cor(indigenousearthquakedata$O_PER_num, indigenousearthquakedata$avg_1, method = "pearson")
     library(tidyverse)
     newmodel <- lm(indigenousearthquakedata$O_PER_num, indigenousearthquakedata$indigenous_township ~ indigenousearthquakedata$avg_1)
     cor(indigenousearthquakedata$indigenous_township,indigenousearthquakedata$O_PER_num, method = "pearson")
     regress <- lm(indigenousearthquakedata$O_PER_num~indigenousearthquakedata$avg_1)
     summary(regress)
     
     